import { escapeHtml, formatDate, formatMoney } from '../lib/format.js';

export function renderCash(state) {
  const active = state.activeCash;
  const sessionPayments = active ? state.payments.filter((item) => item.cashSessionId === active.id) : [];
  const collected = sessionPayments.reduce((sum, item) => sum + Number(item.amountCents || 0), 0);
  const cashCollected = sessionPayments.filter((item) => item.method === 'cash').reduce((sum, item) => sum + Number(item.amountCents || 0), 0);
  const expectedCash = active ? Number(active.openingCents) + cashCollected : 0;
  return `
    <section class="panel-heading"><div><span class="eyebrow">Control de caja</span><h2>${active ? 'Caja abierta' : 'Inicia tu jornada'}</h2><p>Registra apertura, cobros y cierre con diferencia calculada.</p></div><div class="status-chip ${active ? 'online' : 'muted'}"><i data-lucide="circle-dollar-sign"></i>${active ? 'Sesión activa' : 'Sin sesión'}</div></section>
    ${active ? `<div class="metric-grid"><article class="metric-card"><i data-lucide="wallet"></i><div><span>Fondo inicial</span><strong>${formatMoney(active.openingCents)}</strong></div></article><article class="metric-card positive"><i data-lucide="badge-dollar-sign"></i><div><span>Cobrado total</span><strong>${formatMoney(collected)}</strong></div></article><article class="metric-card"><i data-lucide="calculator"></i><div><span>Efectivo esperado</span><strong>${formatMoney(expectedCash)}</strong></div></article></div><section class="surface-card cash-action"><div><span class="eyebrow">Abierta por ${escapeHtml(active.openedByName)}</span><h3>${formatDate(active.openedAt,true)}</h3><p>${escapeHtml(active.notes || 'Sin notas de apertura.')}</p></div><form id="cash-close-form" class="inline-form"><input type="hidden" name="expected" value="${expectedCash}"><label>Efectivo contado<input name="closing" type="number" min="0" step="0.01" required></label><label>Nota<input name="notes" maxlength="500"></label><button class="button danger" type="submit">Cerrar caja</button></form></section>` : `<section class="surface-card empty-action"><i data-lucide="wallet-cards"></i><div><h3>Abre una caja para registrar cobros</h3><p>El fondo inicial formará parte del arqueo final.</p></div><form id="cash-open-form" class="inline-form"><label>Fondo inicial<input name="opening" type="number" min="0" step="0.01" value="0" required></label><label>Nota<input name="notes" maxlength="500" placeholder="Turno, responsable…"></label><button class="button primary" type="submit">Abrir caja</button></form></section>`}
    <section class="surface-card data-surface"><header><div><span class="eyebrow">Historial</span><h3>Sesiones recientes</h3></div></header><div class="table-scroll"><table><thead><tr><th>Responsable</th><th>Apertura</th><th>Fondo</th><th>Cierre</th><th>Diferencia</th><th>Estado</th></tr></thead><tbody>${state.cashSessions.map((item) => `<tr><td>${escapeHtml(item.openedByName || 'Usuario')}</td><td>${formatDate(item.openedAt,true)}</td><td>${formatMoney(item.openingCents)}</td><td>${item.status === 'closed' ? formatMoney(item.closingCents) : '—'}</td><td>${item.status === 'closed' ? formatMoney(item.varianceCents) : '—'}</td><td><span class="document-status ${item.status === 'open' ? 'status-paid' : ''}">${item.status === 'open' ? 'Abierta' : 'Cerrada'}</span></td></tr>`).join('')}</tbody></table></div></section>`;
}

export function renderSettings(state) {
  const item = state.settings || {};
  return `
    <section class="panel-heading"><div><span class="eyebrow">Configuración</span><h2>Identidad y facturación</h2><p>Solo el propietario puede modificar estos valores.</p></div></section>
    <form id="settings-form" class="surface-card settings-form stack-form"><div class="form-section"><h3>Negocio</h3><div class="form-grid two"><label>Nombre comercial<input name="name" required maxlength="160" value="${escapeHtml(item.name || '')}"></label><label>Razón social<input name="legalName" maxlength="160" value="${escapeHtml(item.legalName || '')}"></label></div><div class="form-grid three"><label>RNC<input name="rnc" maxlength="30" value="${escapeHtml(item.rnc || '')}"></label><label>Teléfono<input name="phone" maxlength="30" value="${escapeHtml(item.phone || '')}"></label><label>Correo<input name="email" type="email" maxlength="160" value="${escapeHtml(item.email || '')}"></label></div><label>Dirección<textarea name="address" maxlength="300">${escapeHtml(item.address || '')}</textarea></label></div><div class="form-section"><h3>Documentos</h3><div class="form-grid three"><label>Prefijo factura<input name="invoicePrefix" required maxlength="12" value="${escapeHtml(item.invoicePrefix || 'PAN-')}"></label><label>Prefijo cotización<input name="quotePrefix" required maxlength="12" value="${escapeHtml(item.quotePrefix || 'COT-')}"></label><label>Prefijo proforma<input name="proformaPrefix" required maxlength="12" value="${escapeHtml(item.proformaPrefix || 'PROF-')}"></label></div><div class="form-grid two"><label>ITBIS predeterminado %<input name="defaultTaxRate" type="number" min="0" max="100" step="0.01" value="${item.defaultTaxRate ?? 0}"></label><label>Pie de recibo<input name="receiptFooter" maxlength="300" value="${escapeHtml(item.receiptFooter || '')}"></label></div></div><footer class="form-footer"><button class="button primary" type="submit"><i data-lucide="save"></i> Guardar configuración</button></footer></form>`;
}
